### ISSUE TITLE
Run programs to update desktop integration

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#27] opened 2018-12-07 07:34 UTC
https://github.com/AppImage/appimaged/pull/50 from @rszibele needs to be ported over here.

It checks if the following programs are available in the users `$PATH`:
* update-desktop-database
* update-mime-database
* gtk-update-icon-cache
* kbuildsycoca5

Based on the availability of each program, it executes each of them within a thread if more than 3 seconds have passed since the last AppImage was added. If another AppImage is dropped into one of the watched directories while still within the 3 seconds, then the timer is reset. __So if suddenly a user drops 20 AppImages into the directory, the update will only be executed once.__

**Comment by TheAssassin** [comment] 2019-03-01 18:31
Duplicate of #29.

**Closed by TheAssassin** 2019-03-01 18:31 UTC
Labels: PRs welcome, enhancement
