### ISSUE TITLE
Make it possible to find out libappimage version

### ISSUE THREAD

**Issue by probonopd** [AppImage/libappimage#113] opened 2019-05-10 06:13 UTC
How can I find out, by inspecting the binaries, which version of `libappimage` this contains?

```
me@host:~$ '/home/me/Downloads/appimaged-x86_64.AppImage' --version
+appimaged, continuous build (commit 334ff48), build 143 built on 2019-05-10 05:55:51 UTC
```

If would be good if the version was somewhere built into `libappimage` (e.g., as a string that is shown in verbose mode) so that one can easily find out.

**Comment by TheAssassin** [comment] 2019-05-14 22:11
Duplicate of #97.

**Closed by TheAssassin** 2019-05-14 22:11 UTC
Labels: duplicate
